spring:
  application:
    name: CONFIG-DEV
eureka:
  instance:
    prefer-ip-address: true
    #instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    #instance-id: ${spring.application.name}:${random.uuid}
    #appname: CONFIG-DEV
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
